Tnode *create_new_node(int key);
Tnode *leftRotate(Tnode *a);
Tnode *insert(Tnode *node, int key);
int getBalance(Tnode *N);
Tnode *leftRotate(Tnode *a);
Tnode *rightRotate(Tnode *a);
void preOrder(Tnode *root, FILE *ptr);
int max(int a, int b);
int height(Tnode *N);
Tnode *deleteNode(Tnode *root, int key);
Tnode *get_predecesor(Tnode *node);
void deallocate (Tnode * node);